### ISSUE TITLE
Not compiling in Raspberry Pi

### ISSUE THREAD

**Issue by Razican** [mbevand/silentarmy#44]
When compiling in Raspberry Pi, I get this error:
```
gcc  -std=gnu99 -pedantic -Wextra -Wall -ggdb -Wno-deprecated-declarations -Wno-overlength-strings -I"/opt/AMDAPPSDK-3.0/include"  -c -o main.o main.c
main.c:22:18: error: conflicting types for ‘ulong’
 typedef uint64_t ulong;
                  ^
In file included from /usr/include/stdlib.h:314:0,
                 from main.c:3:
/usr/include/arm-linux-gnueabihf/sys/types.h:150:27: note: previous declaration of ‘ulong’ was here
 typedef unsigned long int ulong;
                           ^
main.c: In function ‘print_sol’:
main.c:594:5: warning: left shift count >= width of type
     if (*nonce < (1UL << 32))
     ^
main.c:594:16: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     if (*nonce < (1UL << 32))
                ^
main.c:595:2: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
  fprintf(stderr, " 0x%lx:", *nonce);
  ^
main.c: In function ‘mining_mode’:
main.c:1071:13: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
             printf("status: %ld %ld\n", total, total_shares);
             ^
main.c:1071:13: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
main.c: In function ‘run_opencl’:
main.c:1114:6: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
      total, (t1 - t0) / 1e3, total / ((t1 - t0) / 1e6));
      ^
<builtin>: recipe for target 'main.o' failed
make: *** [main.o] Error 1
```

GCC version:
```
gcc (Raspbian 4.9.2-10) 4.9.2
```

LD version:
```
GNU ld (GNU Binutils for Raspbian) 2.25
```

Seems it's an issue between 64/32 bit compatibility. The first error seems a redefinition of `ulong`, that seems to be already defined in Raspbian.

**Comment by mbevand** [comment]
I pushed a potential fix, can you try recompiling?
https://github.com/mbevand/silentarmy/commit/740f845549820b86b8a3b097057286977f344db1

**Comment by zeechs** [comment]
Hi,
I had the same issue on a Debian Jessie with gcc 4.9.2 (if that matters)
It seems I cloned the project right before you pushed your last commit hehe.
After pulling the update, it now compiles fine and it is mining right now
Thank you !

**Comment by mbevand** [comment]
Great! I am tentatively closing this issue for now. @Razican will reopen it if necessary.

**Comment by Razican** [comment]
It does compile, even though it's still showing this warning:
```
main.c: In function ‘print_sol’:
main.c:593:5: warning: left shift count >= width of type
     if (*nonce < (1UL << 32))
     ^
main.c:593:16: warning: comparison of unsigned expression < 0 is always false [-Wtype-limits]
     if (*nonce < (1UL << 32))
                ^
main.c:594:2: warning: format ‘%lx’ expects argument of type ‘long unsigned int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
  fprintf(stderr, " 0x%lx:", *nonce);
  ^
main.c: In function ‘mining_mode’:
main.c:1068:13: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 2 has type ‘uint64_t’ [-Wformat=]
             printf("status: %ld %ld\n", total, total_shares);
             ^
main.c:1068:13: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
main.c: In function ‘run_opencl’:
main.c:1111:6: warning: format ‘%ld’ expects argument of type ‘long int’, but argument 3 has type ‘uint64_t’ [-Wformat=]
      total, (t1 - t0) / 1e3, total / ((t1 - t0) / 1e6));
```

Thanks!

**Comment by mbevand** [comment]
Get my very latest commit to fix all 32-bit compilation warnings:
https://github.com/mbevand/silentarmy/commit/6ee811daad5019ec288c51572a244f87a1c1c521

**Comment by Razican** [comment]
Cool! it now compiles perfectly!
